// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXKXDHlReF7L0Ye3F-lE709nW3uFJft98',
    appId: '1:25811519913:web:6b3dfaef0ef5af614f1cb8',
    messagingSenderId: '25811519913',
    projectId: 'mini-project-flutter-2025',
    authDomain: 'mini-project-flutter-2025.firebaseapp.com',
    storageBucket: 'mini-project-flutter-2025.firebasestorage.app',
    measurementId: 'G-XP6C6MF8NQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXlDBlLhokA8OoXSxTkwL0Rc6m7THFG30',
    appId: '1:25811519913:android:9e2a82299a6abb5f4f1cb8',
    messagingSenderId: '25811519913',
    projectId: 'mini-project-flutter-2025',
    storageBucket: 'mini-project-flutter-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQJ3kFtXPY_t4RJmeYYgx99GM59oGD7TE',
    appId: '1:25811519913:ios:f6d42a9fb631f4d64f1cb8',
    messagingSenderId: '25811519913',
    projectId: 'mini-project-flutter-2025',
    storageBucket: 'mini-project-flutter-2025.firebasestorage.app',
    iosBundleId: 'com.example.miniproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQJ3kFtXPY_t4RJmeYYgx99GM59oGD7TE',
    appId: '1:25811519913:ios:f6d42a9fb631f4d64f1cb8',
    messagingSenderId: '25811519913',
    projectId: 'mini-project-flutter-2025',
    storageBucket: 'mini-project-flutter-2025.firebasestorage.app',
    iosBundleId: 'com.example.miniproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXKXDHlReF7L0Ye3F-lE709nW3uFJft98',
    appId: '1:25811519913:web:a0023e56b66d26bf4f1cb8',
    messagingSenderId: '25811519913',
    projectId: 'mini-project-flutter-2025',
    authDomain: 'mini-project-flutter-2025.firebaseapp.com',
    storageBucket: 'mini-project-flutter-2025.firebasestorage.app',
    measurementId: 'G-DTF76TFCDR',
  );
}
